apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
 name: simple-supplychain
spec:
  resources:
  - templateRef:
      kind: ClusterSourceTemplate
      name: source-template
    name: source-provider
  - templateRef:
      kind: ClusterImageTemplate
      name: image-template
    name: build-image
    sources:
    - name: source
      resource: source-provider
    params:
    - name: registry
      value:
        server: harbor.emea.end2end.link
        repository: tap-wkld
  - templateRef:
      kind: ClusterConfigTemplate
      name: app-config-template
    name: app-config
    images:
    - name: image
      resource: build-image
  - templateRef:
      kind: ClusterTemplate
      name: deployment-template
    name: deploy
    config:
    - name: config
      resource: app-config
  selector:
    apps.tanzu.vmware.com/workload-type: web
    simple: "true"
