apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: custom-kaniko-template
spec:
  params:
    - name: serviceAccount
      default: default
    - name: registry
      default: {}
    - name: dockerfile
      default: ./Dockerfile
  imagePath: .status.outputs.latest-image

  ytt: |
    #@ load("@ytt:data", "data")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def image():
    #@   return "/".join([
    #@    data.values.params.registry.server,
    #@    data.values.params.registry.repository,
    #@    "-".join([
    #@      data.values.workload.metadata.name,
    #@      data.values.workload.metadata.namespace,
    #@    ])
    #@   ])
    #@ end

    #@ def context_sub_path():
    #@   return data.values.workload.spec.source.git.url.replace("https://github.com/","").replace(".git","").replace("/","-") + "-" + data.values.source.revision[0:7]
    #@ end

    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: #@ data.values.workload.metadata.name + "-kaniko"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "build" })
    spec:
      #@ if/end hasattr(data.values.workload.spec, "serviceAccountName"):
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName

      runTemplateRef:
        name: custom-kaniko-template

      inputs:
        serviceAccount: #@ data.values.params.serviceAccount
        image: #@ image()
        dockerfile: #@ data.values.params.dockerfile
        git-url: #@ data.values.workload.spec.source.git.url
        source-url: #@ data.values.sources.source.url
        source-revision: #@ data.values.sources.source.revision
        source-subpath: #@ context_sub_path()