apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: custom-supply-chain-workshop
spec:
  params:
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: image-builder
    params:
      - name: serviceAccount
        value: default
      - name: clusterBuilder
        value: default
      - name: registry
        value:
          repository: tap-wkld
          server: harbor.emea.end2end.link
      - name: dockerfile
        default: ./Dockerfile
      - name: docker_build_context
        default: ./
      - name: docker_build_extra_args
        default: []
    sources:
      - name: source
        resource: source-provider
    templateRef:
        kind: ClusterImageTemplate
        options:
          - name: kpack-template
            selector:
              matchFields:
                - key: spec.params[?(@.name=="dockerfile")]
                  operator: DoesNotExist
          - name: kaniko-template
            selector:
              matchFields:
                - key: spec.params[?(@.name=="dockerfile")]
                  operator: Exists
  selector:
    apps.tanzu.vmware.com/workload-type: web
    end2end.link/workshop-session: prod-w03-s045