apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: dev-space
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - '*'
- apiGroups:
  - source.apps.tanzu.vmware.com
  resources:
  - imagerepositories
  verbs:
  - '*'
- apiGroups:
  - carto.run
  resources:
  - deliverables
  - runnables
  verbs:
  - '*'
- apiGroups:
  - kpack.io
  resources:
  - images
  verbs:
  - '*'
- apiGroups:
  - conventions.apps.tanzu.vmware.com
  resources:
  - podintents
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - taskruns
  - pipelineruns
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  verbs:
  - list
- apiGroups:
  - kappctrl.k14s.io
  resources:
  - apps
  verbs:
  - '*'
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings
  verbs:
  - '*'
- apiGroups:
  - services.apps.tanzu.vmware.com
  resources:
  - resourceclaims
  verbs:
  - '*'
- apiGroups:
  - scanning.apps.tanzu.vmware.com
  resources:
  - imagescans
  - sourcescans
  verbs:

cat <<EOF | kubectl apply -f - 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
EOF