apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-app
  labels:
    app.kubernetes.io/part-of: python-app
    apps.tanzu.vmware.com/workload-type: web
    end2end.link/workshop-session: prod-w03-s045
spec:
  params:
  - name: dockerfile
    value: ./Dockerfile
  source:
    git:
      url: https://github.com/tsalm-pivotal/spring-boot-hello-world.git
      ref:
        branch: main
