apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-source-controller
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: harbor.emea.end2end.link/tap-workshop/github-source-controller
        name: user-container