apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: custom-supply-chain-workshop
spec:
  params: []
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterSourceTemplate
      name: custom-github-source-template
  - name: image-builder
    params:
      - name: serviceAccount
        value: default
      - name: clusterBuilder
        value: default
      - name: registry
        value:
          repository: tap-wkld
          server: harbor.emea.end2end.link
      - name: dockerfile
        default: ./Dockerfile
    sources:
      - name: source
        resource: source-provider
    templateRef:
        kind: ClusterImageTemplate
        options:
          - name: kpack-template
            selector:
              matchFields:
                - key: spec.params[?(@.name=="dockerfile")]
                  operator: DoesNotExist
          - name: custom-kaniko-template
            selector:
              matchFields:
                - key: spec.params[?(@.name=="dockerfile")]
                  operator: Exists
  - name: deployment
    params:
    - name: ingressDomain
      value: emea.end2end.link
    - name: tlsSecretName
      value: tanzu-system-ingress/cnr-contour-tls-delegation-cert
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterTemplate
      name: custom-deployment-template
    images:
    - resource: image-builder
      name: image
  selector:
    apps.tanzu.vmware.com/workload-type: web
    end2end.link/workshop-session: prod-w03-s045