#@data/values
---
tap:
  ingress_domain: tap.example.com
  cnrs_subdomain: cnr.tap.example.com
container_registry:
  hostname: harbor.example.com
  username: admin
  password:
  repository: tap-wkld
workshop_git:
  username: user
  branch: main
tanzunet:
  username: user@example.com
  password:
gitops:
  ssh_repository_prefix: git@github.com:tsalm-pivotal/supply-chain-choreographer
  ssh_private_key:_ssh_private_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----