apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: supply-chain-choreographer-workshops
spec:
  portal:
    title: Workshops for Supply Chain Choreographer
    ingress:
        hostname: supply-chain-choreographer-workshops
    registration:
        type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 40
    reserved: 1
  workshops:
    - name: supply-chain-choreographer-workshop
      expires: 200m
      orphaned: 200m