apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: custom-github-source-template
spec:
  params:
  - name: serviceAccount
    default: default

  urlPath: .status.artifact.url
  revisionPath: .status.artifact.revision

  ytt: |
    #@ load("@ytt:data", "data")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    ---
    apiVersion: timosalm.de/v1
    kind: GitHubRepository
    metadata:
      name: #@ data.values.workload.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "source" })
    spec:
      url: #@ data.values.workload.spec.source.git.url
      branch: #@ data.values.workload.spec.source.git.ref.branch