apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: python-app
    apps.tanzu.vmware.com/workload-type: web
    end2end.link/workshop-session: prod-w03-s045
  name: custom-supply-chain-workshop
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tsalm-pivotal/python-hello-world-workshop-example.git